### ISSUE TITLE
Favicons not working with mdx-deck dev server?

### ISSUE THREAD

**Issue by jsjoeio** [trevorblades/emoji-favicon-webpack-plugin#4]
Hi @trevorblades 👋 !

First, thanks for making this! 🎉 

### Context

So I followed the instructions in the [README](https://github.com/trevorblades/emoji-favicon-webpack-plugin/tree/master/examples/mdx-deck) and tested it out with `mdx-deck` and the rocket showed up as the favicon. However, when I changed the icon, and restarted the dev server, it stopped working and showed the 'blank' favicon. BUT, it does work in the static output when I build the `mdx-deck`. 

I'm not sure why it wouldn't work with the dev sever though? 🤔 Not sure if it's an issue with your library, or mdx-deck but thought I should let you know here.

### Steps to Reproduce

1. Create a new mdx-deck
2. Follow [these instructions](https://github.com/trevorblades/emoji-favicon-webpack-plugin/tree/master/examples/mdx-deck) to add the favicon to your mdx-deck.
3. Run `npm start` to see your mdx-deck
4. Go to your `webpack.config.js` and change the icon to 💯 
5. Stop the dev server then run `npm start` again. 

### Expected
The favicon should be the 💯 

### Actual
No favicon is shown.

Here's [my repo](https://github.com/jsjoeio/build-chrome-exts-react) if you want to reproduce it.

**Comment by trevorblades** [comment]
@jsjoeio I tried to reproduce the problem using your repo, but I was unable to 😕 here's a screencap of me changing the favicon a few times: https://gfycat.com/TerribleTheseAdouri

It does make me curious about why this wouldn't be working on your end. If you fire up the mdx-deck dev server and then hit http://localhost:8080/favicon.ico in your browser, does the icon load?

**Comment by jsjoeio** [comment]
@trevorblades something weird is happening 🙈 

Yeah, looks like it's working great for you. Not sure why it's acting funny on my side. Here's a video of me demonstrating the weirdness: https://res.cloudinary.com/dobfxs62e/video/upload/v1543701600/Screen_Recording_2018-12-01_at_2.54.57_PM_pgcp9b.mov

The icon does load if I hit /favicon.ico

I'm really not too sure what could be causing it? 🤷‍♂️  But I appreciate you taking a look! Happy to close this if you want.

**Comment by trevorblades** [comment]
That's really odd! In the case of the rocket favicon, it seems like some kind of browser caching issue, which I've also encountered in the past with other projects. The blank icon is a bit more puzzling 🤔

It's good to see the actual favicon.ico file getting updated, though. Do you get any different results if you load/reload the project in an incognito window?

**Comment by jsjoeio** [comment]
Okay this thing is not playing nicely. Now I can't reproduce the blank icon error 😑 

So I was able to get it working - in a regular window & incognito. 

I just had to restart the mdx-deck. Weird. Sorry for the trouble man!

**Comment by trevorblades** [comment]
@jsjoeio no worries! Glad you were able to get it working 🚀
